import type { NextPage } from 'next'
import { gql, useQuery } from '@apollo/client';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import AwesomeLink from '../components/Links';


const LinksQuery = gql`
  query LinksQuery {
    links {
      id
      index
      title
      url
      description
      imageUrl
      category
    }
  }

`

const Home: NextPage = () => {

  const {data, loading, error} = useQuery(LinksQuery);

  if(loading) return <p>Loading....</p>
  if(error) return <p>Error: {error.message}</p>

  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container mx-auto max-w-5xl my-20 px-5'>
        <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 '>
          {data?.links.map(link => (
            <Link href={`/link/${link.id}`} key={link.id}>
             <a>
              <AwesomeLink
                title={link.title}
                category={link.category}
                url={link.url}
                id={link.id}
                description={link.description}
                imageUrl={link.imageUrl}
              />
              </a> 
            </Link>
          ))}

        </div>
      </div>
      
    </div>
  )
}

export default Home
